-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'LEAVE_REQUEST_PENDING';
ALTER TYPE "NotificationType" ADD VALUE 'LEAVE_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'LEAVE_REQUEST_REJECTED';
